DROP TABLE IF EXISTS `iot_status_log`;
CREATE TABLE IF NOT EXISTS `iot_status_log` (
  `log_id` int(11) NOT NULL AUTO_INCREMENT,
  `DID` varchar(100) COLLATE utf8_bin NOT NULL,
  `CMD` varchar(100) COLLATE utf8_bin NOT NULL,
  `USR` varchar(20) COLLATE utf8_bin NOT NULL,
  `PWD` varchar(20) COLLATE utf8_bin NOT NULL,
  `G01M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G01V` int(11) NOT NULL,
  `G02M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G02V` int(11) NOT NULL,
  `G03M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G03V` int(11) NOT NULL,
  `G04M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G04V` int(11) NOT NULL,
  `G05M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G05V` int(11) NOT NULL,
  `G06M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G06V` int(11) NOT NULL,
  `G07M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G07V` int(11) NOT NULL,
  `G08M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G08V` int(11) NOT NULL,
  `G09M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G09V` int(11) NOT NULL,
  `G10M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G10V` int(11) NOT NULL,
  `G11M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G11V` int(11) NOT NULL,
  `G12M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G12V` int(11) NOT NULL,
  `G13M` varchar(50) COLLATE utf8_bin NOT NULL,
  `G13V` int(11) NOT NULL,

  `A0M` varchar(50) COLLATE utf8_bin NOT NULL,
  `A0V` int(11) NOT NULL,
  `A1M` varchar(50) COLLATE utf8_bin NOT NULL,
  `A1V` int(11) NOT NULL,
  `A2M` varchar(50) COLLATE utf8_bin NOT NULL,
  `A2V` int(11) NOT NULL,
  `A3M` varchar(50) COLLATE utf8_bin NOT NULL,
  `A3V` int(11) NOT NULL,
  `A4M` varchar(50) COLLATE utf8_bin NOT NULL,
  `A4V` int(11) NOT NULL,
  `A5M` varchar(50) COLLATE utf8_bin NOT NULL,
  `A5V` int(11) NOT NULL,

  `request_datetime` varchar(100) COLLATE utf8_bin NOT NULL,
  `log_datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  UNIQUE KEY `log_id` (`log_id`),
  KEY `log_datetime` (`log_datetime`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='LOG of Request Response Interactions' AUTO_INCREMENT=1 ;



